//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.16 at 12:19:37 PM AST 
//


package by.javatr.webparsing.service.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VisualParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisualParameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transparencyPr" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="facesNumber" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisualParameters", propOrder = {
    "color",
    "transparencyPr",
    "facesNumber"
})
public class VisualParameters {

    @XmlElement(required = true)
    protected String color;
    protected double transparencyPr;
    protected double facesNumber;

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getColor() {
        return this.color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the transparencyPr property.
     *
     */
    public double getTransparencyPr() {
        return this.transparencyPr;
    }

    /**
     * Sets the value of the transparencyPr property.
     * 
     */
    public void setTransparencyPr(double value) {
        this.transparencyPr = value;
    }

    /**
     * Gets the value of the facesNumber property.
     *
     */
    public double getFacesNumber() {
        return this.facesNumber;
    }

    /**
     * Sets the value of the facesNumber property.
     * 
     */
    public void setFacesNumber(double value) {
        this.facesNumber = value;
    }

    @Override
    public String toString() {
        return "VisualParameters{" +
                "color='" + color + '\'' +
                ", transparencyPr=" + transparencyPr +
                ", facesNumber=" + facesNumber +
                '}';
    }
}
